import * as React from 'react';

import {
  dirnameOf,
  isFileSchemeUrl,
  isPurelyRelativeAssetPath,
  resolveLocalAssetSrc,
} from '../../core/resolveLocalAssetSrc';
import { refreshLines } from '../../extensions/editor/ScrollSync';
import { sonnerToast } from '../../notify';
import { logger } from '../../util';
import { useFiles } from '../contexts/FilesContext';
import { useFileTree } from '../contexts/FileTreeContext';
import { useManagers } from '../contexts/ManagersContext';
import { useTranslation } from '../hooks/useTranslation';

// Markdown.ts pulls in markdown-it, KaTeX, highlight.js core + 13
// language modules — ~400 KB of code that isn't needed until the
// preview renders its first frame. Dynamic-import it once on mount
// so it lands in a separate chunk and stays out of the main bundle.
type MarkdownAPI = typeof import('../../core/Markdown').Markdown;
let markdownPromise: Promise<MarkdownAPI> | null = null;
function loadMarkdown(): Promise<MarkdownAPI> {
  if (!markdownPromise) {
    markdownPromise = import('../../core/Markdown').then((m) => m.Markdown);
  }
  return markdownPromise;
}

/**
 * Renders the markdown preview. Subscribes to `editor:render`; on each
 * event runs `Markdown.render(editorManager.getValue())` and writes the
 * result into `#preview-content`. The innerHTML write is intentional:
 * markdown-it produces HTML strings (see HTMLExporter risk note).
 *
 * Refs:
 * - Outer `#preview` div is read by ScrollSync via `dom.preview.wrapper`.
 * - Inner `#preview-content` div is read by HTMLExporter via
 *   `dom.preview.dom.outerHTML` and by ExportSettingsProvider for live
 *   styling. Both dom.ts getters re-query at access time, so they pick
 *   up these React-rendered elements once they mount.
 */
export const PreviewPane: React.FC = () => {
  const { mode, editorManager, dispatcher, fileManager } = useManagers();
  const { activeFile } = useFiles();
  const { treeRoot } = useFileTree();
  const { t } = useTranslation();
  const contentRef = React.useRef<HTMLDivElement>(null);

  const activeEditablePath = React.useMemo(
    () => fileManager?.getActiveEditablePath() ?? null,
    [fileManager, activeFile],
  );

  // Stash the latest base-resolution info in a ref so the `render`
  // closure (created once when the effect runs) reads the current
  // values on every dispatch — without re-running the effect (which
  // would tear down and re-bind the editor:render listener and reload
  // the markdown chunk on every tab switch).
  const baseInfoRef = React.useRef({ mode, activeEditablePath, treeRoot });
  React.useEffect(() => {
    baseInfoRef.current = { mode, activeEditablePath, treeRoot };
  }, [mode, activeEditablePath, treeRoot]);

  React.useEffect(() => {
    let cancelled = false;
    let md: MarkdownAPI | null = null;

    const render = () => {
      if (!contentRef.current || !md) return;
      const html = md.render(editorManager?.getValue() ?? '');
      contentRef.current.innerHTML = '';
      contentRef.current.appendChild(
        buildPreviewFragment(html, baseInfoRef.current),
      );
      refreshLines();
    };

    // Load Markdown once, then wire up the render handler. While the
    // chunk is in flight, any editor:render dispatches are silently
    // dropped — the catch-up `render()` call after the load handles
    // the initial state, and subsequent edits stay within the editor's
    // debounce window so nothing visible is lost.
    void loadMarkdown().then((api) => {
      if (cancelled) return;
      md = api;
      render();
    });

    dispatcher.addEventListener('editor:render', render);
    return () => {
      cancelled = true;
      dispatcher.removeEventListener('editor:render', render);
    };
  }, [dispatcher, editorManager]);

  // Re-render the preview whenever the asset base directory changes
  // (new tab opens, workspace folder swapped). Without this, the
  // preview would only refresh on the next content edit, and image
  // URLs would still point at the previous file's directory.
  React.useEffect(() => {
    dispatcher.render();
  }, [activeEditablePath, treeRoot, dispatcher]);

  // Event delegation for the per-codeblock copy button. The button is
  // generated by Markdown.ts inside an innerHTML write, so React can't
  // bind onClick directly — instead we listen on the host once and walk
  // up to find the `.md-codeblock` wrapper. The original source is
  // stashed there as a base64 `data-source` attribute (avoids reading
  // hljs span fragments from textContent).
  React.useEffect(() => {
    const node = contentRef.current;
    if (!node) return;

    const onClick = (event: MouseEvent) => {
      const target = event.target as HTMLElement | null;
      const btn = target?.closest('.md-codeblock-copy') as HTMLElement | null;
      if (!btn) return;
      const wrapper = btn.closest('.md-codeblock') as HTMLElement | null;
      const encoded = wrapper?.getAttribute('data-source');
      if (!encoded) return;
      try {
        const binary = atob(encoded);
        const bytes = Uint8Array.from(binary, (c) => c.charCodeAt(0));
        const text = new TextDecoder().decode(bytes);
        void navigator.clipboard
          .writeText(text)
          .then(() => sonnerToast('success', t('navbar:code_copied')));
      } catch (err) {
        logger?.error('PreviewPane.copy', JSON.stringify(err));
      }
    };

    node.addEventListener('click', onClick);
    return () => node.removeEventListener('click', onClick);
  }, [t]);

  return (
    <div id="preview" className="flex flex-col split-preview p-3">
      <div ref={contentRef} id="preview-content" className="container-fluid" />
    </div>
  );
};

/**
 * Parse the rendered markdown HTML into an off-DOM `<template>` so we
 * can rewrite relative `<img>` and `<a>` URLs before the browser
 * starts fetching them. Without this rewrite, a relative image like
 * `![](collector.png)` resolves against the bundle's `dist/` directory
 * and 404s — the file actually lives in the workspace folder.
 *
 * Only runs in desktop mode. Web mode would need to async-resolve
 * each handle into a blob URL (separate workstream).
 */
function buildPreviewFragment(
  html: string,
  ctx: {
    mode: 'web' | 'desktop';
    activeEditablePath: string | null;
    treeRoot: string | null;
  },
): DocumentFragment {
  const template = document.createElement('template');
  template.innerHTML = html;

  if (ctx.mode !== 'desktop') return template.content;

  // Prefer the active editable file's directory so `![](sibling.png)`
  // works the way CommonMark prescribes; fall back to the workspace
  // root so a freshly-mounted preview without an open file still
  // resolves image paths to something useful.
  let baseDir: string | null = null;
  if (ctx.activeEditablePath) {
    baseDir = dirnameOf(ctx.activeEditablePath);
  } else if (ctx.treeRoot) {
    baseDir = ctx.treeRoot;
  }

  const imgs = template.content.querySelectorAll('img');
  for (const img of imgs) {
    const src = img.getAttribute('src');
    if (!src) continue;
    const resolved = resolveLocalAssetSrc(src, {
      baseDir,
      workspaceRoot: ctx.treeRoot,
    });
    if (resolved) {
      img.setAttribute('src', resolved);
    } else if (!baseDir && isPurelyRelativeAssetPath(src)) {
      // Transitional render: first paint fires after the markdown
      // chunk loads but before session restore has propagated the
      // active file into FilesContext, so we don't yet know which
      // directory to resolve against. Blank the src so the browser
      // doesn't 404 against the bundle's `dist/` directory — the
      // re-render triggered by activeFile/treeRoot landing puts the
      // correct `file:///…` URL in place a moment later.
      img.removeAttribute('src');
    } else if (isFileSchemeUrl(src)) {
      // Explicit `file://...` URL that the resolver rejected.
      img.removeAttribute('src');
    }
  }
  // Same treatment for anchor hrefs that point at on-disk assets
  // (PDFs, images opened as links). Markdown links that resolve to
  // `.md` siblings are intercepted by MkedLinkProvider into `mked://`
  // URLs upstream and won't match here (the scheme check short-
  // circuits the resolver).
  const anchors = template.content.querySelectorAll('a[href]');
  for (const a of anchors) {
    const href = a.getAttribute('href');
    if (!href) continue;
    const resolved = resolveLocalAssetSrc(href, {
      baseDir,
      workspaceRoot: ctx.treeRoot,
    });
    if (resolved) {
      a.setAttribute('href', resolved);
    } else if (isFileSchemeUrl(href)) {
      // Same containment policy as <img>: `file://...`.
      a.removeAttribute('href');
    }
  }

  return template.content;
}
